"""create users services checks and incidents

Revision ID: 70b499397a7b
Revises:
Create Date: 2026-08-26 14:49:31.175516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b499397a7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=2048), nullable=False),
    sa.Column('check_type', sa.Enum('http', 'ping', 'tcp_port', name='check_type'), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('expected_status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.CheckConstraint('expected_status_code IS NULL OR (expected_status_code >= 100 AND expected_status_code <= 599)', name='ck_services_expected_status_range'),
    sa.CheckConstraint('interval_seconds >= 10', name='ck_services_interval_minimum'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_created_by'), ['created_by'], unique=False)

    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_up', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.create_index('ix_checks_service_timestamp', ['service_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_checks_timestamp'), ['timestamp'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name='ck_incidents_duration_nonnegative'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incidents_service_started', ['service_id', 'started_at'], unique=False)
        batch_op.create_index(
            'uq_incidents_one_open_per_service',
            ['service_id'],
            unique=True,
            postgresql_where=sa.text('resolved_at IS NULL'),
            sqlite_where=sa.text('resolved_at IS NULL'),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(
            'uq_incidents_one_open_per_service',
            postgresql_where=sa.text('resolved_at IS NULL'),
            sqlite_where=sa.text('resolved_at IS NULL'),
        )
        batch_op.drop_index('ix_incidents_service_started')

    op.drop_table('incidents')
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checks_timestamp'))
        batch_op.drop_index('ix_checks_service_timestamp')

    op.drop_table('checks')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_created_by'))

    op.drop_table('services')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        check_type = sa.Enum('http', 'ping', 'tcp_port', name='check_type')
        check_type.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
